### ISSUE TITLE
no connection with ejabbered, but prosody works

### ISSUE THREAD

**Issue by georg-mayer** [markstory/hubot-xmpp#123]
Hello,

I am aware that most likely there will not be much response here, but I give it a try, as hubot via xmpp is a true companion since a long time and I don't want to lose it.

hubot-xmpp was working fine under prosody, but now I had to switch to ejabberd. hubot-xmpp makes it's first connection, but then this happens:

```
[Sun Jan 27 2019 20:01:57 GMT+0100 (CET)] INFO { username: 'bot@example.com',
  password: '********',
  host: 'example.com',
  port: '5222',
  rooms: [ { jid: 'bottalk@conference.example.com', password: false } ],
  keepaliveInterval: 30000,
  reconnectTry: 5,
  reconnectWait: 5000,
  legacySSL: undefined,
  preferredSaslMechanism: undefined,
  disallowTLS: undefined,
  pmAddPrefix: undefined }
(node:11975) [DEP0010] DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
[Sun Jan 27 2019 20:01:58 GMT+0100 (CET)] INFO Hubot XMPP client online
[Sun Jan 27 2019 20:01:58 GMT+0100 (CET)] INFO Hubot XMPP sent initial presence
[Sun Jan 27 2019 20:01:58 GMT+0100 (CET)] INFO hubot-redis-brain: Using default redis on localhost:6379
[Sun Jan 27 2019 20:01:58 GMT+0100 (CET)] INFO hubot-redis-brain: Data for hubot brain retrieved from Redis
[Sun Jan 27 2019 20:02:00 GMT+0100 (CET)] WARNING Could not get private JID from group chat. Make sure the server is configured to broadcast real jid for groupchat (see http://xmpp.org/extensions/xep-0045.html#enter-nonanon)
[Sun Jan 27 2019 20:02:00 GMT+0100 (CET)] ERROR TypeError: Cannot read property 'toString' of null
    at new User (/root/cottbot/node_modules/hubot/src/user.coffee:9:23)
    at Brain.userForId (/root/cottbot/node_modules/hubot/src/brain.coffee:106:14)
    at XmppBot.readPresence (/root/cottbot/node_modules/hubot-xmpp/src/xmpp.coffee:361:29)
    at XmppBot.readPresence (/root/cottbot/node_modules/hubot-xmpp/src/xmpp.coffee:1:1)
    at XmppBot.read (/root/cottbot/node_modules/hubot-xmpp/src/xmpp.coffee:221:10)
    at Client.<anonymous> (/root/cottbot/node_modules/hubot-xmpp/src/xmpp.coffee:1:1)
    at emitOne (events.js:116:13)
    at Client.emit (events.js:211:7)
    at Client._handleStanza (/root/cottbot/node_modules/node-xmpp-client/lib/Client.js:228:12)
    at Client.onStanza (/root/cottbot/node_modules/node-xmpp-client/lib/Client.js:222:8)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.onStanza (/root/cottbot/node_modules/node-xmpp-core/lib/Connection.js:369:10)
    at StreamParser.<anonymous> (/root/cottbot/node_modules/node-xmpp-core/lib/Connection.js:226:10)
    at emitOne (events.js:116:13)
    at StreamParser.emit (events.js:211:7)
    at SaxLtx.<anonymous> (/root/cottbot/node_modules/node-xmpp-core/lib/StreamParser.js:58:14)
    at emitOne (events.js:116:13)
    at SaxLtx.emit (events.js:211:7)
    at SaxLtx._handleTagOpening (/root/cottbot/node_modules/ltx/lib/parsers/ltx.js:37:12)
    at SaxLtx.write (/root/cottbot/node_modules/ltx/lib/parsers/ltx.js:111:18)
    at StreamParser.write (/root/cottbot/node_modules/node-xmpp-core/lib/StreamParser.js:123:17)
    at Connection.onData (/root/cottbot/node_modules/node-xmpp-core/lib/Connection.js:305:17)
    at emitOne (events.js:121:20)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:607:20)
```

The beginning looks identical to when I let it run under prosody, but then this line is the first real difference:
```
[Sun Jan 27 2019 20:02:00 GMT+0100 (CET)] WARNING Could not get private JID from group chat. Make sure the server is configured to broadcast real jid for groupchat (see http://xmpp.org/extensions/xep-0045.html#enter-nonanon)
```
So I went to ejabberd and configured it to show all private JIDs from groupchat

```
    mod_muc:                                                                                                       
        ## host: "conference.@HOST@"                                                                                 
        default_room_options:                                                                                        
          anonymous: false                                                                                           
          public_list: true                                                                                          
          public: true                                                                                               
        access:                                                                                                      
          - allow                                                                                                    
        access_admin:                                                                                                
          - allow: admin                        
```

I'm not sure what else to do now - I updated everything and the error keeps coming up. 

Any type of hint or help would be greatly welcome!

Thanks and cheers,
Georg
